
host:
    loopback:
        ip: 10.101.3.3

interfaces:
    - name: ge-0/0/1
      ip: 192.168.56.203
      description: Management_vboxnet0
    - name: ge-0/0/2
      vlans:
      - id: 1
        ip: 10.1.3.1
        description: to vsrx-CE3-white
      - id: 2
        ip: 10.2.3.1
        description: to vsrx-CE3-black
    - name: ge-0/0/3
      ip: 10.100.6.1
      description: to vsrx-PE4
      protocols:
      - iso
      - mpls      
    - name: ge-0/0/4
      ip: 10.100.3.2
      description: to vsrx-P1
      protocols:
      - iso
      - mpls      

isis:
    systemid: 49.0002.0010.0101.0003.0003.00

bgp:
    neighbors:
        - name: vsrx-P1
          peer_ip: 10.101.5.5        
