host:
    loopback:
        ip: 10.201.1.1
        units:
        - prefix: 10.11.1.1/24
          description: ce1-black
          value: 1
        - prefix: 10.22.1.1/24
          description: ce1-white
          value: 11
        - prefix: 10.11.3.1/24
          description: ce3-black
          value: 3
        - prefix: 10.22.3.1/24
          description: ce3-white
          value: 33
        - prefix: 10.11.4.1/24
          description: ce4-black
          value: 4
        - prefix: 10.22.4.1/24
          description: ce4-white
          value: 44        

interfaces:
    - name: ge-0/0/1
      ip: 192.168.56.205
      description: Management_vboxnet0
    - name: ge-0/0/2
      vlans:
        - id: 1
          ip: 10.1.1.2
          description: to vsrx-PE1-white
        - id: 2
          ip: 10.2.1.2
          description: to vsrx-PE1-black
    - name: ge-0/0/3
      vlans:
        - id: 1
          ip: 10.1.2.2
          description: to vsrx-PE2-white
        - id: 2
          ip: 10.2.2.2
          description: to vsrx-PE2-black
    - name: ge-0/0/4
      vlans:
        - id: 1
          ip: 10.1.3.2
          description: to vsrx-PE3-white
        - id: 2
          ip: 10.2.3.2
          description: to vsrx-PE3-black
    - name: ge-0/0/5
      vlans:
        - id: 1
          ip: 10.1.4.2
          description: to vsrx-PE4-white
        - id: 2
          ip: 10.2.4.2
          description: to vsrx-PE4-black

instances:
  - name: ce1-black
    type: virtual-router
    interfaces:
    - name: ge-0/0/2.1
    - name: lo0.1
    routes:
      - prefix: 0.0.0.0/0
        nexthop: 10.1.1.1
  - name: ce1-white
    type: virtual-router
    interfaces:
    - name: ge-0/0/2.2
    - name: lo0.11
    routes:
      - prefix: 0.0.0.0/0
        nexthop: 10.2.1.1    
  - name: ce2-black
    type: virtual-router
    interfaces:
    - name: ge-0/0/3.1
    routes:
      - prefix: 0.0.0.0/0
        nexthop: 10.1.2.1    
  - name: ce2-white
    type: virtual-router
    interfaces:
    - name: ge-0/0/3.2 
    routes:
      - prefix: 0.0.0.0/0
        nexthop: 10.2.2.1    
  - name: ce3-black
    type: virtual-router
    interfaces:
    - name: ge-0/0/4.1
    - name: lo0.3
    routes:
      - prefix: 0.0.0.0/0
        nexthop: 10.1.3.1    
  - name: ce3-white
    type: virtual-router
    interfaces:
    - name: ge-0/0/4.2
    - name: lo0.33
    routes:
      - prefix: 0.0.0.0/0
        nexthop: 10.2.3.1    
  - name: ce4-black
    type: virtual-router
    interfaces:
    - name: ge-0/0/5.1
    - name: lo0.4
    routes:
      - prefix: 0.0.0.0/0
        nexthop: 10.1.4.1    
  - name: ce4-white 
    type: virtual-router
    interfaces:
    - name: ge-0/0/5.2
    - name: lo0.44
    routes:
      - prefix: 0.0.0.0/0
        nexthop: 10.2.4.1